
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Administrator
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
        this.setResizable(false); //Set the frame fix you cant resize the frame anymore
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png"))); //set image icon
        txtFirstname.setBackground(new java.awt.Color(0,0,0,1)); //set the background to transparent
        txtLastname.setBackground(new java.awt.Color(0,0,0,1)); //set the background to transparent
        txtAddress.setBackground(new java.awt.Color(0,0,0,1)); //set the background to transparent
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLastname = new javax.swing.JTextField();
        txtFirstname = new javax.swing.JTextField();
        cboCity = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        btnInsert = new javax.swing.JLabel();
        btnClear = new javax.swing.JLabel();
        btnDelete = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRecords = new javax.swing.JTable();
        cboGender = new javax.swing.JComboBox<>();
        btnUpdate1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLastname.setBackground(new java.awt.Color(255, 255, 255));
        txtLastname.setColumns(1);
        txtLastname.setFont(txtLastname.getFont());
        txtLastname.setBorder(null);
        txtLastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 380, 30));

        txtFirstname.setBackground(new java.awt.Color(255, 255, 255));
        txtFirstname.setColumns(1);
        txtFirstname.setFont(txtFirstname.getFont());
        txtFirstname.setBorder(null);
        txtFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 380, 40));

        cboCity.setBackground(new java.awt.Color(255, 255, 255));
        cboCity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cboCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bacolod", "Baguio", "Batangas", "Cagayan de Oro", "Caloocan", "Cebu", "Cavite", "Davao", "Iloilo", "Makati", "Manila", "Pasay", "Pasig", "Quezon City", "Tagaytay" }));
        getContentPane().add(cboCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 380, 30));

        txtAddress.setBackground(new java.awt.Color(255, 255, 255));
        txtAddress.setColumns(20);
        txtAddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAddress.setRows(5);
        txtAddress.setBorder(null);
        jScrollPane1.setViewportView(txtAddress);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 476, 400, 160));

        btnInsert.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnInsert.setForeground(new java.awt.Color(0, 51, 102));
        btnInsert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnInsert.setText("Insert");
        btnInsert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertMouseClicked(evt);
            }
        });
        getContentPane().add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 660, 130, 50));

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(0, 51, 102));
        btnClear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClear.setText("Clear");
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 730, 120, 60));

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 51, 102));
        btnDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDelete.setText("Delete");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 730, 130, 60));

        tblRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Firstname", "Lastname", "Gender", "City", "Date", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRecords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRecordsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblRecords);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 760, 620));

        cboGender.setBackground(new java.awt.Color(255, 255, 255));
        cboGender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(cboGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 316, 380, 30));

        btnUpdate1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdate1.setForeground(new java.awt.Color(0, 51, 102));
        btnUpdate1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUpdate1.setText("Update");
        btnUpdate1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdate1MouseClicked(evt);
            }
        });
        getContentPane().add(btnUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 660, 120, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Logout");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Homepage (3).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastnameActionPerformed

    private void txtFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstnameActionPerformed

    private void btnInsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertMouseClicked
        // retrieves the text from txtFirstname and txtLastname text fields, the selected item from cboGender and cboCity combo boxes
        String firstname = txtFirstname.getText();
        String lastname = txtLastname.getText();
        String gender = cboGender.getSelectedItem().toString();
        String city = cboCity.getSelectedItem().toString();
        String address = txtAddress.getText();
        // values are then added to a new row in the JTable tblRecords
        DefaultTableModel model = (DefaultTableModel)tblRecords.getModel();
        model.addRow(new Object[]{firstname, lastname, gender, city, address});
    }//GEN-LAST:event_btnInsertMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // this line of code clears all amd display a message dialog
        DefaultTableModel model = (DefaultTableModel)tblRecords.getModel();
        int rows = model.getRowCount()-1;
        for(int i=rows; i>=0; i--){
            model.removeRow(i);
        }
        JOptionPane.showMessageDialog(null, "The table is now empty!");
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // this line of code allows you to delete a row inside the table
        DefaultTableModel model = (DefaultTableModel)tblRecords.getModel();
        model.removeRow(tblRecords.getSelectedRow());
        JOptionPane.showMessageDialog(null, "Record deleted successfuly!");
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnUpdate1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdate1MouseClicked
        // this line of code allows you to select and edit a line of row inside the table
        String firstname = txtFirstname.getText();
        String lastname = txtLastname.getText();
        String gender = cboGender.getSelectedItem().toString();
        String city = cboCity.getSelectedItem().toString();
        String address = txtAddress.getText();
        DefaultTableModel model = (DefaultTableModel)tblRecords.getModel();
        model.setValueAt(firstname, tblRecords.getSelectedRow(), 0);
        model.setValueAt(lastname, tblRecords.getSelectedRow(), 1);
        model.setValueAt(gender, tblRecords.getSelectedRow(), 2);
        model.setValueAt(city, tblRecords.getSelectedRow(), 3);
        model.setValueAt(address, tblRecords.getSelectedRow(), 5);
        JOptionPane.showMessageDialog(null, "Record updated succesfully");
    }//GEN-LAST:event_btnUpdate1MouseClicked

    private void tblRecordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRecordsMouseClicked
        //this line of code allows you to select a row inside the table
        DefaultTableModel model = (DefaultTableModel)tblRecords.getModel();
        String firstname = model.getValueAt(tblRecords.getSelectedRow(), 0).toString();
        String lastname = model.getValueAt(tblRecords.getSelectedRow(), 1).toString();
        String gender = model.getValueAt(tblRecords.getSelectedRow(), 2).toString();
        String city = model.getValueAt(tblRecords.getSelectedRow(), 3).toString();
        String date = model.getValueAt(tblRecords.getSelectedRow(), 4).toString();
        String address = model.getValueAt(tblRecords.getSelectedRow(), 5).toString();
    }//GEN-LAST:event_tblRecordsMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        //this line of code allows you to go back to the login frame basically a logout button
        CRUD2 login = new CRUD2();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClear;
    private javax.swing.JLabel btnDelete;
    private javax.swing.JLabel btnInsert;
    private javax.swing.JLabel btnUpdate1;
    private javax.swing.JComboBox<String> cboCity;
    private javax.swing.JComboBox<String> cboGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblRecords;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLastname;
    // End of variables declaration//GEN-END:variables
}
